#!/bin/sh

echo "Running pre-install script in $2"

# Comment out user dialog section
#CORE_AUDIO_CHECK_RESULT=$(osascript -s o <<EOF
#    set results to (display dialog "The Core Audio background process (coreaudiod) will be restarted, and audio will be interrupted.\n\nContinue with the installation?" with title "Install Dante Virtual Soundcard" with icon caution buttons {"Continue", "Cancel"} default button "Continue")
#    set button_clicked to button returned of results
#    if button_clicked = "Cancel" then
#        return ""
#    end if
#    return "Continue"
#EOF
#)

# Comment out the check for user response
#if [[ $CORE_AUDIO_CHECK_RESULT != "Continue" ]]; then
#    exit 1
#fi

# Unload manager
launchctl unload -w /Library/LaunchDaemons/com.audinate.dante.DanteVirtualSoundcard.plist > /dev/null 2>&1

# Unload driver if exists
if [ $(kextstat | grep -c com.audinate.dante.driver.NetworkAudioDriver) -ne 0 ]; then
    kextunload -b com.audinate.dante.driver.NetworkAudioDriver > /dev/null 2>&1
fi

if [ $(kextstat | grep -c com.audinate.dante.driver.DanteVirtualSoundcard) -ne 0 ]; then
    kextunload -b com.audinate.dante.driver.DanteVirtualSoundcard > /dev/null 2>&1
fi

# Remove DVS Audio PlugIn
rm -rf /Library/Audio/Plug-Ins/HAL/DvsAudioPlugIn.driver

# Remove DVS apps
rm -rf /Library/Application\ Support/Audinate/DanteVirtualSoundcard
rm -rf /Applications/Dante\ Virtual\ Soundcard*

# Force quit DVS if it's already running
killall "Dante Virtual Soundcard"

exit 0
